services:
  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - HOST=0.0.0.0

  backend:
    build:
      context: ./backend
      target: dev
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    volumes:
      - ./backend:/app

  mongodb:
    image: mongo:6
    container_name: database_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
